### ISSUE TITLE
Photos not showing in all areas

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#10]
The photos associated to the review dont show in all areas. On the page https://dfs.andrewshemo.com/reviews-category-1-brushes you will see no photos (true on the default theme too). 

On Profile, the user widget has images, the merchant not, see image1. The images show on the main page, but not in the subsections, see image 2.

**Image1**
![reviewprofile](https://cloud.githubusercontent.com/assets/1857551/20640405/3f3b2c4e-b3dd-11e6-8054-deeeed9c290e.JPG)

**Image 2**
![reviewsubs](https://cloud.githubusercontent.com/assets/1857551/20640428/ebe07fbc-b3dd-11e6-8906-7473b5a396b2.JPG)

**Comment by andrewjs18** [comment]
to add onto this...in my opinion, the photos should also be clickable so that it loads into the actual review.

from a UX point of view, it makes it much easier to use the review system.

**Comment by dvz** [comment]
Fixed some inconsistencies in https://github.com/DamnFineShave/mybb-CommunityReviews/commit/b1a2cbada88f6959c21dcb970a5c0928b2a9b608 - let me know if the bug with no thumbnail persists.

**Comment by andrewjs18** [comment]
I think it looks good now.  I'll let @leefish play around some to see if she sees any issues before we can close this.

edited to add: @Devilshakerz, can we make the photos clickable so they go inside the reviews?

**Comment by leefish** [comment]
Clickable images would indeed be awesome :) I did rewrite the template as Andrew wanted a different look and I went with this code:

`<div class="holder">

<img src={$thumbnailUrl}" alt="{$lang->community_reviews_product_photo}"/>

</div>`

Though I was unable to make a link through to the product work. I did try 

`<a href={$url}>image</a>`

But that of course opened the full size image on imgur

**Comment by dvz** [comment]
With https://github.com/DamnFineShave/mybb-CommunityReviews/commit/2984207b6311a91e8d2100c67a3a464bff31ab40 you should be able to use `{$product['url']}` within the `product_card_photo` template.

**Comment by leefish** [comment]
Excellent :) Thank you very much

**Comment by andrewjs18** [comment]
this should be good to go.
