### ISSUE TITLE
enhancement: image uploads

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#13]
it'd be nice if these enhancements were made to the image upload process:
1- show the image upload progress
2- allow the user to pick which photo should be used as the thumbnail.

**Comment by dvz** [comment]
Updating - execute SQL:
```ALTER TABLE `mybb_community_reviews_photos` ADD COLUMN `order` int(11) DEFAULT 0```
and reactivate the plugin.
