### ISSUE TITLE
Add ability to change product type when editing a product

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#16]
Example: a user adds a product in Category 1 instead of Category 2. Editing the product only gives the option to edit the name. 

I would class this as an enhancement, but I cant add the label

**Comment by andrewjs18** [comment]
@leefish, @Devilshakerz made a good point about this issue in slack to me.  if we allow a user to edit their product category, then we'll also need to change all of their rating fields as they'd change.  

on top of that, I imagine switching the rating fields would cause all of the user's data to be lost.  for example..what if category 1 has 6 rating fields but category 2 only has 4?  what happens to that extra data?

I think we'll probably just have to make the user's delete and redo their reviews if it's in the wrong category.

**Comment by andrewjs18** [comment]
I think we're going to table this one for now.
