### ISSUE TITLE
User review widget star rating

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#17]
I think the user review widget should show the users rating of a product, not the overall rating. If I grade a product 1 star, and everyone else grades it 5, then it looks like I like product when I dont as the average will be a lot higher than my rating of one.

**Comment by andrewjs18** [comment]
where are you seeing the review widget showing any stars anyhow?  I don't see it on @Devilshakerz test forum or my test forum...  :(

that aside, I agree with you that if we do show review stars in the user widget, it should be based on the user's review, not the overall rating.

**Comment by dvz** [comment]
> where are you seeing the review widget showing any stars anyhow? I don't see it on @Devilshakerz test forum or my test forum... :(

My test forum has not been updated, but the rating might not show when there are no fields assigned to the category yet.

**Comment by leefish** [comment]
Thank you for the fix to the star rating, but I see that for some reason the number of reviews is "doubled" in the user widget, see images: 

![review](https://cloud.githubusercontent.com/assets/1857551/20858966/70cceb5c-b951-11e6-8db9-17819ba00dd5.JPG)


only one review on the product page:

![onlyone](https://cloud.githubusercontent.com/assets/1857551/20858968/7eba1e06-b951-11e6-93cd-19eb687726d9.JPG)

**Comment by dvz** [comment]
Should be fixed by https://github.com/DamnFineShave/mybb-CommunityReviews/commit/64028d117928630544c3c12f24218bfbe4cee26e

**Comment by leefish** [comment]
Yes, this fixed. Thank you.
