### ISSUE TITLE
Variable for the community widget?

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#19]
What is the variable for the community reviews widget on the forum index?

**Comment by dvz** [comment]
That would be `$community_reviews_widget`

**Comment by leefish** [comment]
I thought so, but it isnt showing :( Is there something else I need to do?

**Comment by leefish** [comment]
ok, found it, it didnt like being in the sidebar for some reason :) 

can you add the clickable image to this widget as well please? I tried

 `
<a href="{$product['url']}"><img class="x" src={$thumbnailUrl}" alt="{$lang->community_reviews_product_photo}"/></a>`

But that did not work.

Also, the ellipse is not working correctly in the widget:

![widget](https://cloud.githubusercontent.com/assets/1857551/20858309/a01e3f40-b943-11e6-84b5-7bcec2c5fc79.JPG)

**Comment by dvz** [comment]
Fixed the title (https://github.com/DamnFineShave/mybb-CommunityReviews/commit/4fb02294435fb91671b3aac203eaed71efc03fa2); `{$url}` should give you the URL in `widget_entry_photo`

**Comment by leefish** [comment]
Excellent, thank you very much. I turned the widget into a slider :)

https://dfs.andrewshemo.com/

**Comment by andrewjs18** [comment]
this can be closed.
