### ISSUE TITLE
enhancement: include reviews in mybb's search functionality

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#20]
right now I do not believe any of the reviews will appear in mybb's default search system.  I think this is necessary, especially as the review system grows in size with time.

**Comment by leefish** [comment]
I don't think this is an enhancement in the sense of "nice to have", this is really needed, as once the number of pages gets big then looking for existing products to add a review to is going to be exhausting. That usually will mean users will start just adding new products, which is going to be a workload and a half in the merging.

**Comment by andrewjs18** [comment]
agreed, @leefish.  if only 1 or 2 things were to get fixed/added over the new week or two, I'd say that this and the permissions are the two top priorities.

**Comment by dvz** [comment]
Upgrading:
 - execute SQL command (change the table prefix if necessary):
   ```sql
   CREATE FULLTEXT INDEX `name` ON mybb_community_reviews_products(`name`);
   ```
- add new rewrite rules: https://github.com/DamnFineShave/mybb-CommunityReviews/commit/14581acbb687c1c0a7b9470716300aa36bf78380#diff-04c6e90faac2675aa89e2176d2eec7d8
- requirements bumped to MySQL >= 5.6 (MariaDB >= 10.0.5) with InnoDB

**Comment by leefish** [comment]
Hi, what is the variable for the search in the sidebar?

**Comment by dvz** [comment]
Currently it gets prepended to `{$sectionSideContent}` on its own.

**Comment by leefish** [comment]
It is always appearing above the rest of the sidebar. How can I move it?

I would like the option to put it anywhere I like on the page.

**Comment by dvz** [comment]
https://github.com/DamnFineShave/mybb-CommunityReviews/commit/05d8397143afe47dc676a6db7cc9b8be8266bf3b: `{$searchForm}` now available within the `page` template
