### ISSUE TITLE
enhancement: make permissions more granular

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#21]
right now, all of the permissions seemed to be tied together into a 'yes' or 'no' option.  there needs to be more granular control over specific permissions so we don't run into issues where a rogue user goes around editing/deleting all reviews, whether they're his or not.

for example, right now when I grant user group A the permission to moderate reviews (this is the only available permission I see), that user can edit and delete any review in the system, whether it's their own review or not.  this is bad for several reasons.

**Comment by dvz** [comment]
Upgrading:
 - reinstall the plugin or add two new settings manually:
   -  Title: `Group permissions: Deleting own content`
      Description: `User groups that can delete own reviews.`
      Group: `Community Reviews`
      Identifier: `community_reviews_groups_delete_own`
      Type: `Group Selection Box`

   -  Title: `Group permissions: Editing own content`
      Description: `User groups that can edit own reviews.`
      Group: `Community Reviews`
      Identifier: `community_reviews_groups_edit_own`
      Type: `Group Selection Box`

**Comment by leefish** [comment]
This is working as expected thank you
