### ISSUE TITLE
alerts - what all triggers an alert?

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#23]
per the alert settings in the user cp, the only action that seems to trigger an alert is when a merchant is tagged in a review.  is there anything else that triggers an alert?

I thought we discussed adding alerts for reviews that are similar to the default myalerts settings: if someone adds a review and/or comment to my review, trigger an alert.  also allow this to be turned off/on in the alerts settings in the user cp.

right now the alert system will be very underutilized for the review system.

**Comment by andrewjs18** [comment]
bump, @Devilshakerz

**Comment by dvz** [comment]
Updating - reinstall the MyAlerts integration
