### ISSUE TITLE
enhancement: allow the category list to be ordered in the admin cp

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#28]
I think the ability to rearrange the order of the categories in the admin cp is useful.  I think something as simple as adding a number box next to the category name would suffice just fine - exactly the same as the default mybb forum ordering is set up and used.

**Comment by dvz** [comment]
Updating - execute SQL:
```ALTER TABLE `mybb_community_reviews_categories` ADD COLUMN `order` int(11) NOT NULL```
