### ISSUE TITLE
nginx rewrites don't appear to be working

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#29]
the nginx rewrites, per https://github.com/DamnFineShave/mybb-CommunityReviews/blob/master/README.md don't appear to be working correctly..I've restarted both nginx & php-fpm on my server.

here's my entire nginx rewrite block in my vhost config:

           

                #Mybb Rewrites
                rewrite ^/([^&]*)&(.*)$ https://mysite.com/$1?$2 permanent;

                # Google SEO Sitemap:
                rewrite ^/((?i)sitemap-([^./]+)\.xml)$ /misc.php?google_seo_sitemap=$2;

                # Google SEO URL Forums:
                rewrite ^/((?i)forum-([^./]+))$ /forumdisplay.php?google_seo_forum=$2;

                # Google SEO URL Threads:
                rewrite ^/((?i)thread-([^./]+))$ /showthread.php?google_seo_thread=$2;

                # Google SEO URL Announcements:
                rewrite ^/((?i)announcement-([^./]+))$ /announcements.php?google_seo_announcement=$2;

                # Google SEO URL Users:
                rewrite ^/((?i)user-([^./]+))$ /member.php?action=profile&google_seo_user=$2;

                # Google SEO URL Calendars:
                rewrite ^/((?i)calendar-([^./]+))$ /calendar.php?google_seo_calendar=$2;

                # Google SEO URL Events:
                rewrite ^/((?i)event-([^./]+))$ /calendar.php?action=event&google_seo_event=$2;

                # Community Reviews
                rewrite ^/reviews$ /index.php?action=reviews last;
                rewrite ^/reviews-search$ /index.php?action=reviews&search=1 last;
                rewrite ^/reviews-category-([0-9]+)-[0-9a-z_-]+$ /index.php?action=reviews&category=$1 last;
                rewrite ^/reviews-product-([0-9]+)-[0-9a-z_-]+$ /index.php?action=reviews&product=$1 last;
                rewrite ^/reviews-merchant-([0-9]+)$ /index.php?action=reviews&merchant=$1 last;

**Comment by andrewjs18** [comment]
strange.  these starting working after changing Enable search engine friendly URLs? from disabled to enabled in  Home » Board Settings » Server and Optimization Options.  

why is that, @Devilshakerz?

**Comment by dvz** [comment]
Upgrading:
- reinstall the plugin or add a new setting:
   - Title: `Search engine friendly URLs`
   - Description: `Use friendly URLs when linking to Community Reviews pages. Requires plugin's rewrite rules present in the server configuration.`
   - Group: `Community Reviews`
   - Identifier: `community_reviews_seo_urls`
   - Type: `Yes / No Choice`
