### ISSUE TITLE
enhancement: add button to link a specific review in the comments

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#32]
since the review system doesn't use the traditional thread/reply system, there currently isn't a way for a user to reply to a specific review in the comments.  I think the easiest way to 'solve' this without a drastic overhaul is to add a button somewhere in the review area where a user can click on it and it'll automatically append the review URL in a new comment they'd make, like so:

this is my comment

https://mysite.com/some-review?review1=#review1

**Comment by dvz** [comment]
Updating - execute SQL:
```
ALTER TABLE `mybb_community_reviews_comments` ADD COLUMN `review_id` int(11) AFTER `product_id`, ADD FOREIGN KEY (`review_id`) REFERENCES `mybb_community_reviews`(`id`) ON DELETE CASCADE;
```
