### ISSUE TITLE
linking reviews in comments isn't working

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#36]
I know you're aware of this issue but I figured I'd open an issue on github so it can be tracked.

when clicking on the button to link a review to a comment, it doesn't do anything when submitting the comment.  the review_id column is being set to NULL in the database.

**Comment by dvz** [comment]
Updated `product.tpl` in https://github.com/DamnFineShave/mybb-CommunityReviews/commit/dadac7d785b7ab974352b5ab14cd604fc5075fd5#diff-b599ee0668600b8e0ffb3cd388b7b764
