### ISSUE TITLE
Using tabs on member profile

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#4]
I use tabs on the member profile; I only want a reviews tab to show if there are reviews for that member. I use template conditionals, do you have a template conditional code to make the tab with the reviews only visible when there are reviews?

**Comment by andrewjs18** [comment]
As far as I know, this code hasn't been implemented yet.  @Devilshakerz, any thoughts?

**Comment by dvz** [comment]
> As far as I know, this code hasn't been implemented yet.

Yes, after some refurbishment `$community_reviews_user_widget` will be available to display user's reviews and both user- and merchant- related (`$community_reviews_merchant_widget`) variables will be empty if no entries are found, so a simple `<if>` in the profile template using Template Conditionals would do the trick.

**Comment by leefish** [comment]
Thank you, so what variable can I use then?

**Comment by dvz** [comment]
`$community_reviews_user_widget` and `$community_reviews_merchant_widget` should output latest reviews posted by the user and those in which they were tagged, respectively.
If there's something to show, they contain entries generated from the `product_card` template, wrapped in `user_widget` or `merchant_widget`.
ICYMI I've just pushed some fixes to `inc/plugins/community_reviews/hooks_frontend.php`.

**Comment by leefish** [comment]
Can you just say what the variable is please?

**Comment by dvz** [comment]
Can you elaborate? Don't these mentioned work?

**Comment by leefish** [comment]
So are you saying I can use `"<if $community_reviews_user_widget then>my stuff</if>"`  ?

Another question, What if a merchant has reviews of their product, but has also made reviewsof another merchants product? how does the plugin manage that?

**Comment by dvz** [comment]
That code should work (same with `<if $community_reviews_merchant_widget then>my stuff</if>`).

Both of those can be displayed simultaneously, so they can be put in separate tabs (a list of the merchant's products that were recently reviewed and reviews that the same user has posted).
