### ISSUE TITLE
create plugin setting for default category sorting

### ISSUE THREAD

**Issue by andrewjs18** [DamnFineShave/mybb-CommunityReviews#45]
right now the default sorting option in the plugin settings only seems to apply to the review index.  we'd like to see that option renamed so we know it's for the review index as well as a new sorting option added to categories.

currently the review system is set up to sort the index by newest reviews while the categories are set to sort by Name (A-Z) and there's no way to change that unless you modify the code itself, I believe.

**Comment by dvz** [comment]
New settings:

- Title: `Category view order`
    Description: `Determines how products within a category should be displayed.`
    Group: `Community Reviews`
    Identifier: `community_reviews_category_view_order_column`
    Type: `Selection Box`
    Extra:
    ```
    name=Name
    rating=Rating
    num_reviews=Number of reviews
    views=Number of views
    date=Date
    ```
    Value: `name`

- Title: `Category view order direction`
    Description: `Determines which direction should be used for sorting.`
    Group: `Community Reviews`
    Identifier: `community_reviews_category_view_order_direction`
    Type: `Selection Box`
    Extra:
    ```
    asc=Ascending
    desc=Descending
    ```
    Value: `asc`

**Comment by andrewjs18** [comment]
I'm not sure if this not working is a result of a bug with #46 or not.  I uploaded all of the new files then set the new settings to sort by date and asc.  after saving it and viewing a category with a lot of reviews (https://damnfineshave.com/reviews-category-2-soaps-creams), the sorting seems to be ok (oldest to newest by date - I believe that's how asc should sort it).  when going back in to reverse it to dsc, which is how I want it by default, nothing changed for the sorting, nor am I able to manually apply a sorting filter within a category.

**Comment by andrewjs18** [comment]
fixed with https://github.com/DamnFineShave/mybb-CommunityReviews/commit/77b60256d649da5097f68bbe70a8d8651ab97585
