### ISSUE TITLE
Font awesome vs glyphicons

### ISSUE THREAD

**Issue by leefish** [DamnFineShave/mybb-CommunityReviews#9]
Hi, I cannot find where you are templating in the font awesome for this:

`` <div class="community-reviews__controls">
            <p class="community-reviews__controls__moderation">{$reportLink}{$editLink}{$deleteLink}{$mergeLink}</p>
            <p class="community-reviews__controls__id"><a href="{$productUrl}">#{$product['id']}</a></p>
        </div>
``

As DFS uses Bootstrap, rather than loading another icon font the built in Glyphicons are used instead. Where can I change this?

**Comment by dvz** [comment]
I was afraid somebody would want to use another set ;)
Some were hardcoded for the plugin to be easy on the template system, however there aren't much: https://github.com/DamnFineShave/mybb-CommunityReviews/search?utf8=%E2%9C%93&q=fa-fw

I can push a patch moving those to the template system as well if you'd like (in the meantime the HTML can be replaced manually).

**Comment by leefish** [comment]
Yea, I had this with trade feedback. Why dont you make it so its a class, and then the class can be applied via the css? Lot easier :) 

Did you do something similar with the product labels?

**Comment by dvz** [comment]
> Why dont you make it so its a class, and then the class can be applied via the css? Lot easier :)

It should be pretty straightforward to replace all icons with CSS in that case (as FA wouldn't cause conflicts when not included).

**Comment by leefish** [comment]
Is this updated to be a class? Its not that trivial to change the links in the templates :)

**Comment by dvz** [comment]
Have you tried substituting values with Glyphicons equivalents?
```
.fa {
    font-family: 'Glyphicons Regular';
}
```
```
.fa-pencil:before {
    content: "\E151";
}
```
As said, it can be broken down into single templates but it might slow things down.

**Comment by leefish** [comment]
but you are hardcoding the font awesome icons into the php :) For example

` $editLink = '<a href="' . self::url('edit_product', $category['id'], self::toSlug($category['name']), (int)$product['id']) . '" title="' . $lang->community_reviews_edit . '"><i class="fa fa-fw `fa-pencil"></i></a>`

Could be 

 $editLink = `'<a` class="review_edit" href="' . self::url('edit_product', $category['id'], self::toSlug($category['name']), (int)$product['id']) . '" title="' . $lang->community_reviews_edit . `'"></a>`

and so on. No need for extra templates or disguising font awesome as glyphicons in the css

**Comment by dvz** [comment]
It can be changed if it makes things easier, but it will be based on CSS classes nonetheless, hence my question (currently there would be names provided by FA instead of custom ones, thus working with FA out of the box).

**Comment by leefish** [comment]
Yes of course, it should be FA out of the box, but I prefer to keep my classes clear (for me) and turning font awesome into glyphicons in the way you suggest, though it would work, seems not clear .
